const ADD_USER = "ADD_USER";
const FOOT_CHANGE = "FOOT_CHANGE";
const DETAIL_DATA = "DETAIL_DATA";
const SHOPPCAR = "SHOPPCAR";
const SUBTRACT = "SUBTRACT";
export {
    ADD_USER,FOOT_CHANGE,DETAIL_DATA,SHOPPCAR,SUBTRACT
}